### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by montoyamoraga** [montoyamoraga/shlisp-atom#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [shlisp-atom](https://github.com/montoyamoraga/shlisp-atom) package 0.1.1

### Stack Trace

Uncaught SyntaxError: Unexpected identifier

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

/Users/montoyamoraga/.atom/packages/shlisp-atom/lib/shlisp-atom.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import ShlispAtomView from "./shlisp-atom-view";
                                                                                                                                                                  ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at NativeCompileCache.runInThisContext (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146322)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147206)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3233575)
    at Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3222863)
    at PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:935702)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2650759)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2641039)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2640862)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2648992
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2651010
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:945159)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:942291
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:936821)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125033)
    at ChildProcess.o.process.on.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125239)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -7:36.5.0 symbols-view:toggle-file-symbols (div.package-detail)
```

### Non-Core Packages

```
atom-hydra 0.2.14 
atom-live-server 2.3.0 
comments-syntax 1.3.0 
language-babel 2.85.0 
language-chuck 1.0.1 
language-graphql 1.0.0 
language-haskell 1.19.4 
language-supercollider 0.2.1 
monokai 0.24.0 
shlisp-atom 0.1.1 
tidalcycles 3.8.7 
```

**Comment by montoyamoraga** [comment]
the .js files in lib/ where missing the first line
'use babel';
i don't know why, but it's fixed
